services:
  calculix-server:
    image: lukasneo/calculix-server:amd64
    platform: linux/amd64
    pull_policy: always
    ports:
      - "8080:8080"
    environment:
      CCX_THREADS: 8
      UPLOAD_LIMIT_GB: 1
    volumes:
      - ./data:/data
    restart: unless-stopped
